import { describe, expect, it } from "vitest";
import { calculateSale, customerRecordSchema, saleMutationSchema, saleRecordSchema, validateTransactionDate } from "./sales";

const base = { customerId: "11111111-1111-4111-8111-111111111111", transactionDate: "2026-09-15", discountRupiah: 0, feeRupiah: 0, notes: "", paymentChoice: "debt" as const, initialPaymentRupiah: 0, dueDate: "2026-10-15", idempotencyKey: "22222222-2222-4222-8222-222222222222", status: "confirmed" as const };
describe("kontrak dan kalkulasi penjualan", () => {
  it("menghitung per peti hanya dari jumlah peti", () => { const input = saleMutationSchema.parse({ ...base, items: [{ description: "Telur", pricingBasis: "crate", crateQuantity: "10", weightKg: "103.5", unitPriceRupiah: 300000 }] }); expect(calculateSale(input)).toMatchObject({ subtotalRupiah: 3000000, totalRupiah: 3000000, paidRupiah: 0, remainingRupiah: 3000000, paymentStatus: "unpaid" }); });
  it("menghitung 103.5 kg secara presisi serta diskon dan biaya", () => { const input = saleMutationSchema.parse({ ...base, discountRupiah: 10000, feeRupiah: 5000, items: [{ description: "Telur", pricingBasis: "kg", crateQuantity: "10", weightKg: "103.5", unitPriceRupiah: 25000 }] }); expect(calculateSale(input)).toMatchObject({ subtotalRupiah: 2587500, totalRupiah: 2582500 }); });
  it.each([["full", 0, 100000, 0, "paid"], ["down_payment", 40000, 40000, 60000, "partial"], ["debt", 0, 0, 100000, "unpaid"]])("menurunkan status pilihan %s", (choice, initial, paid, remaining, status) => { const raw = { ...base, paymentChoice: choice, initialPaymentRupiah: initial, paymentMethod: choice === "debt" ? undefined : "cash", items: [{ description: "Telur", pricingBasis: "crate", crateQuantity: "1", unitPriceRupiah: 100000 }] }; const result = calculateSale(saleMutationSchema.parse(raw)); expect(result).toMatchObject({ paidRupiah: paid, remainingRupiah: remaining, paymentStatus: status }); });
  it("mewajibkan due date dan menolak input finansial tidak valid", () => { expect(saleMutationSchema.safeParse({ ...base, dueDate: undefined, items: [] }).success).toBe(false); expect(() => calculateSale(saleMutationSchema.parse({ ...base, discountRupiah: 2, items: [{ description: "x", pricingBasis: "crate", crateQuantity: "1", unitPriceRupiah: 1 }] }))).toThrow("negatif"); });
  it("menerima batas backdate tepat satu tahun dan menolak sebelum batas/future dalam WIB", () => { const now = new Date("2026-09-15T03:00:00Z"); expect(validateTransactionDate("2025-09-15", now)).toBeNull(); expect(validateTransactionDate("2025-09-14", now)).toContain("maksimal satu tahun"); expect(validateTransactionDate("2026-09-16", now)).toContain("masa depan"); });
  it("menurunkan status jatuh tempo dan terlambat dari kalender Jakarta", () => { const dueToday = saleMutationSchema.parse({ ...base, dueDate: "2026-09-15", items: [{ description: "Telur", pricingBasis: "crate", crateQuantity: "1", unitPriceRupiah: 100000 }] }); expect(calculateSale(dueToday, "2026-09-15").paymentStatus).toBe("due"); expect(calculateSale(dueToday, "2026-09-16").paymentStatus).toBe("overdue"); });
  it("menolak tanggal kalender semu", () => { expect(saleMutationSchema.safeParse({ ...base, transactionDate: "2026-02-30", items: [{ description: "Telur", pricingBasis: "crate", crateQuantity: "1", unitPriceRupiah: 1 }] }).success).toBe(false); });
  it("menyediakan schema output pelanggan dan penjualan", () => { expect(customerRecordSchema.safeParse({ id: base.customerId, customerNumber: "CUS-1", name: "Budi", whatsapp: null, address: null, notes: null, isActive: true }).success).toBe(true); expect(saleRecordSchema.safeParse({ id: base.customerId, invoiceNumber: "INV-1", idempotencyKey: base.idempotencyKey, totalRupiah: 1, paidRupiah: 0, remainingRupiah: 1, paymentStatus: "unpaid", status: "confirmed" }).success).toBe(true); });
});
