import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { vi } from "vitest";
import { calculateSale, saleMutationSchema, type CustomerRecord } from "@/domain/sales";
import { SaleForm, toSaleInput } from "./sale-form";
import { SALE_DRAFT_KEY } from "./sale-draft";
const push = vi.fn(); const createSaleAction = vi.fn();
vi.mock("next/navigation", () => ({ useRouter: () => ({ push, refresh: vi.fn() }) }));
vi.mock("@/app/actions/f2", () => ({ createSaleAction: (...args: unknown[]) => createSaleAction(...args) }));
const customer: CustomerRecord = { id: "11111111-1111-4111-8111-111111111111", customerNumber: "CUS-1", name: "Budi", whatsapp: null, address: null, notes: null, isActive: true };
describe("SaleForm", () => {
  beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); });
  it("mengganti basis harga dan field pembayaran secara progresif", () => { render(<SaleForm customers={[customer]}/>); expect(screen.getByText("Harga per peti (Rp)")).toBeInTheDocument(); fireEvent.click(screen.getByLabelText("Per kg")); expect(screen.getByText("Harga per kg (Rp)")).toBeInTheDocument(); fireEvent.click(screen.getByLabelText("DP")); expect(screen.getByLabelText("Jumlah DP (Rp)")).toBeInTheDocument(); expect(screen.getByLabelText("Tanggal jatuh tempo")).toBeInTheDocument(); fireEvent.click(screen.getByLabelText("Utang")); expect(screen.queryByLabelText("Jumlah DP (Rp)")).not.toBeInTheDocument(); expect(screen.queryByText("Metode pembayaran *")).not.toBeInTheDocument(); });
  it("mempertahankan input saat retryable error dan mencegah submit ganda", async () => { let resolve!: (value: { ok: false; error: { code: "retryable"; message: string } }) => void; createSaleAction.mockReturnValue(new Promise((done) => { resolve = done; })); render(<SaleForm customers={[customer]}/>); fireEvent.change(screen.getByLabelText("Pelanggan *"), { target: { value: customer.id } }); fireEvent.change(screen.getByLabelText("Jumlah peti"), { target: { value: "10" } }); fireEvent.change(screen.getByLabelText("Harga per peti (Rp)"), { target: { value: "100000" } }); const button = screen.getByRole("button", { name: "Simpan penjualan" }); fireEvent.click(button); fireEvent.click(button); expect(createSaleAction).toHaveBeenCalledTimes(1); resolve({ ok: false, error: { code: "retryable", message: "Coba lagi" } }); await screen.findByText("Coba lagi"); expect(screen.getByLabelText("Jumlah peti")).toHaveValue(10); });
  it("menghapus draft setelah server sukses", async () => { localStorage.setItem(SALE_DRAFT_KEY, "draft"); createSaleAction.mockResolvedValue({ ok: true, data: { id: "sale-1" } }); render(<SaleForm customers={[customer]}/>); fireEvent.change(screen.getByLabelText("Pelanggan *"), { target: { value: customer.id } }); fireEvent.change(screen.getByLabelText("Jumlah peti"), { target: { value: "1" } }); fireEvent.change(screen.getByLabelText("Harga per peti (Rp)"), { target: { value: "1000" } }); fireEvent.click(screen.getByRole("button", { name: "Simpan penjualan" })); await waitFor(() => expect(push).toHaveBeenCalledWith("/penjualan/sale-1?created=1")); expect(localStorage.getItem(SALE_DRAFT_KEY)).toBeNull(); });
});
describe("sale calculation mapping", () => { it("konsisten untuk peti dan kg", () => { const base = { customerId: customer.id, transactionDate: "2026-09-16", description: "Telur", crateQuantity: "10", weightKg: "103.5", unitPriceRupiah: "20000", discountRupiah: "10000", feeRupiah: "5000", notes: "", paymentChoice: "full", initialPaymentRupiah: "0", paymentMethod: "cash", dueDate: "" } as const; const crate = saleMutationSchema.parse(toSaleInput({ ...base, pricingBasis: "crate" }, crypto.randomUUID())); const kg = saleMutationSchema.parse(toSaleInput({ ...base, pricingBasis: "kg" }, crypto.randomUUID())); expect(calculateSale(crate).subtotalRupiah).toBe(200000); expect(calculateSale(kg).subtotalRupiah).toBe(2070000); }); });
