import "server-only";
import { and, desc, eq, ilike, or } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import * as schema from "@/db/schema";
import type { OwnerProfile } from "@/lib/auth/owner";
import { derivePaymentStatus, jakartaDate, type SaleMutationInput } from "@/domain/sales";
import { RepositoryConflictError, RepositoryUnavailableError, type CalculatedSale, type CustomerRecord, type F2Repository, type SaleRecord } from "./repository";

type Db = NodePgDatabase<typeof schema>;
const customerColumns = { id: schema.customers.id, customerNumber: schema.customers.customerNumber, name: schema.customers.name, whatsapp: schema.customers.whatsapp, address: schema.customers.address, notes: schema.customers.notes, isActive: schema.customers.isActive };
const displayNumber = (prefix: string) => `${prefix}-${Date.now()}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`;
function isUniqueViolation(error: unknown): boolean { if (typeof error !== "object" || error === null) return false; if ("code" in error && error.code === "23505") return true; return "cause" in error && isUniqueViolation(error.cause); }
function dbError(error: unknown): never { if (isUniqueViolation(error)) throw new RepositoryConflictError(); throw new RepositoryUnavailableError(error); }

export class DrizzleF2Repository implements F2Repository {
  constructor(private readonly db: Db) {}

  async findCustomerByIdempotencyKey(key: string): Promise<CustomerRecord | null> { try { const [created] = await this.db.select(customerColumns).from(schema.customers).where(eq(schema.customers.createIdempotencyKey, key)).limit(1); if (created) return created; const [event] = await this.db.select({ entityId: schema.auditEvents.entityId }).from(schema.auditEvents).where(and(eq(schema.auditEvents.idempotencyKey, key), eq(schema.auditEvents.entityType, "customer"))).limit(1); return event ? this.getCustomer(event.entityId) : null; } catch (error) { dbError(error); } }
  async createCustomer(input: { idempotencyKey: string; name: string; whatsapp?: string; address?: string; notes?: string }, actor: OwnerProfile): Promise<CustomerRecord> { try { return await this.db.transaction(async (tx) => { const { idempotencyKey, ...values } = input; const [record] = await tx.insert(schema.customers).values({ ...values, createIdempotencyKey: idempotencyKey, customerNumber: displayNumber("CUS") }).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), idempotencyKey, actorId: actor.id, entityType: "customer", entityId: record.id, action: "customer.created", after: record }); return record; }); } catch (error) { dbError(error); } }
  async updateCustomer(input: { id: string; idempotencyKey: string; name?: string; whatsapp?: string; address?: string; notes?: string }, actor: OwnerProfile): Promise<CustomerRecord | null> { try { return await this.db.transaction(async (tx) => { const [before] = await tx.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, input.id)).limit(1); if (!before) return null; const { id, idempotencyKey, ...changes } = input; const [record] = await tx.update(schema.customers).set({ ...changes, updatedAt: new Date() }).where(eq(schema.customers.id, id)).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), idempotencyKey, actorId: actor.id, entityType: "customer", entityId: id, action: "customer.updated", before, after: record }); return record; }); } catch (error) { dbError(error); } }
  async setCustomerActive(id: string, isActive: boolean, idempotencyKey: string, actor: OwnerProfile): Promise<CustomerRecord | null> { try { return await this.db.transaction(async (tx) => { const [before] = await tx.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, id)).limit(1); if (!before) return null; const [record] = await tx.update(schema.customers).set({ isActive, updatedAt: new Date() }).where(eq(schema.customers.id, id)).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), idempotencyKey, actorId: actor.id, entityType: "customer", entityId: id, action: isActive ? "customer.enabled" : "customer.archived", before, after: record }); return record; }); } catch (error) { dbError(error); } }
  async listCustomers(input: { query: string; includeArchived: boolean; limit: number; offset: number }): Promise<CustomerRecord[]> { try { const search = input.query ? or(ilike(schema.customers.name, `%${input.query}%`), ilike(schema.customers.customerNumber, `%${input.query}%`), ilike(schema.customers.whatsapp, `%${input.query}%`)) : undefined; const active = input.includeArchived ? undefined : eq(schema.customers.isActive, true); return await this.db.select(customerColumns).from(schema.customers).where(and(active, search)).orderBy(schema.customers.name).limit(input.limit).offset(input.offset); } catch (error) { dbError(error); } }
  async getCustomer(id: string): Promise<CustomerRecord | null> { try { const [record] = await this.db.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, id)).limit(1); return record ?? null; } catch (error) { dbError(error); } }
  async findSaleByIdempotencyKey(key: string, today: string): Promise<SaleRecord | null> { try { const [sale] = await this.db.select({ id: schema.sales.id, invoiceNumber: schema.sales.invoiceNumber, idempotencyKey: schema.sales.idempotencyKey, totalRupiah: schema.sales.totalRupiah, dueDate: schema.sales.dueDate, status: schema.sales.status }).from(schema.sales).where(eq(schema.sales.idempotencyKey, key)).limit(1); if (!sale) return null; const rows = await this.db.select({ amount: schema.payments.amountRupiah }).from(schema.payments).where(eq(schema.payments.saleId, sale.id)); const paidRupiah = rows.reduce((sum, row) => sum + row.amount, 0); const remainingRupiah = sale.totalRupiah - paidRupiah; return { ...sale, paidRupiah, remainingRupiah, paymentStatus: derivePaymentStatus(remainingRupiah, paidRupiah, sale.dueDate, today), status: sale.status as SaleRecord["status"] }; } catch (error) { dbError(error); } }
  async createSaleAtomic(input: SaleMutationInput, calculated: CalculatedSale, actor: OwnerProfile): Promise<SaleRecord> { try { return await this.db.transaction(async (tx) => { const invoiceNumber = displayNumber("INV"); const [sale] = await tx.insert(schema.sales).values({ invoiceNumber, idempotencyKey: input.idempotencyKey, customerId: input.customerId, status: input.status, paymentStatus: calculated.paymentStatus, transactionDate: new Date(`${input.transactionDate}T00:00:00+07:00`), dueDate: input.dueDate, subtotalRupiah: calculated.subtotalRupiah, discountRupiah: input.discountRupiah, feeRupiah: input.feeRupiah, totalRupiah: calculated.totalRupiah, notes: input.notes, confirmedAt: input.status === "confirmed" ? new Date() : null }).returning({ id: schema.sales.id }); await tx.insert(schema.saleItems).values(calculated.items.map((item) => ({ saleId: sale.id, descriptionSnapshot: item.description, pricingBasis: item.pricingBasis, unitSnapshot: item.unitSnapshot, crateQuantity: item.crateQuantity, weightKg: item.weightKg, pricingQuantity: item.pricingQuantity, unitPriceRupiah: item.unitPriceRupiah, subtotalRupiah: item.subtotalRupiah }))); if (calculated.paidRupiah > 0) await tx.insert(schema.payments).values({ paymentNumber: displayNumber("PAY"), saleId: sale.id, amountRupiah: calculated.paidRupiah, method: input.paymentMethod!, paidAt: new Date(), idempotencyKey: `${input.idempotencyKey}:initial` }); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), idempotencyKey: input.idempotencyKey, actorId: actor.id, entityType: "sale", entityId: sale.id, action: input.status === "confirmed" ? "sale.confirmed" : "sale.drafted", after: { invoiceNumber, totalRupiah: calculated.totalRupiah, paidRupiah: calculated.paidRupiah } }); return { id: sale.id, invoiceNumber, idempotencyKey: input.idempotencyKey, totalRupiah: calculated.totalRupiah, paidRupiah: calculated.paidRupiah, remainingRupiah: calculated.remainingRupiah, dueDate: input.dueDate ?? null, paymentStatus: calculated.paymentStatus, status: input.status }; }); } catch (error) { dbError(error); } }
  async listSales(input: { query: string; limit: number; offset: number }, today: string) { try { const search = input.query ? or(ilike(schema.sales.invoiceNumber, `%${input.query}%`), ilike(schema.customers.name, `%${input.query}%`)) : undefined; const rows = await this.db.select({ id: schema.sales.id, invoiceNumber: schema.sales.invoiceNumber, idempotencyKey: schema.sales.idempotencyKey, totalRupiah: schema.sales.totalRupiah, dueDate: schema.sales.dueDate, status: schema.sales.status, customerName: schema.customers.name, transactionDate: schema.sales.transactionDate }).from(schema.sales).innerJoin(schema.customers, eq(schema.sales.customerId, schema.customers.id)).where(search).orderBy(desc(schema.sales.transactionDate)).limit(input.limit).offset(input.offset); return Promise.all(rows.map(async (sale) => { const payments = await this.db.select({ amount: schema.payments.amountRupiah }).from(schema.payments).where(eq(schema.payments.saleId, sale.id)); const paidRupiah = payments.reduce((sum, row) => sum + row.amount, 0); const remainingRupiah = sale.totalRupiah - paidRupiah; return { ...sale, transactionDate: jakartaDate(sale.transactionDate), status: sale.status as SaleRecord["status"], paidRupiah, remainingRupiah, paymentStatus: derivePaymentStatus(remainingRupiah, paidRupiah, sale.dueDate, today) }; })); } catch (error) { dbError(error); } }
  async getSale(id: string, today: string) { try { const [sale] = await this.db.select({ id: schema.sales.id, invoiceNumber: schema.sales.invoiceNumber, idempotencyKey: schema.sales.idempotencyKey, customerId: schema.sales.customerId, customerName: schema.customers.name, customerNumber: schema.customers.customerNumber, transactionDate: schema.sales.transactionDate, subtotalRupiah: schema.sales.subtotalRupiah, discountRupiah: schema.sales.discountRupiah, feeRupiah: schema.sales.feeRupiah, totalRupiah: schema.sales.totalRupiah, dueDate: schema.sales.dueDate, status: schema.sales.status, notes: schema.sales.notes }).from(schema.sales).innerJoin(schema.customers, eq(schema.sales.customerId, schema.customers.id)).where(eq(schema.sales.id, id)).limit(1); if (!sale) return null; const [items, payments] = await Promise.all([this.db.select({ id: schema.saleItems.id, description: schema.saleItems.descriptionSnapshot, pricingBasis: schema.saleItems.pricingBasis, crateQuantity: schema.saleItems.crateQuantity, weightKg: schema.saleItems.weightKg, unitPriceRupiah: schema.saleItems.unitPriceRupiah, subtotalRupiah: schema.saleItems.subtotalRupiah }).from(schema.saleItems).where(eq(schema.saleItems.saleId, id)), this.db.select({ id: schema.payments.id, amountRupiah: schema.payments.amountRupiah, method: schema.payments.method, paidAt: schema.payments.paidAt }).from(schema.payments).where(eq(schema.payments.saleId, id))]); const paidRupiah = payments.reduce((sum, row) => sum + row.amountRupiah, 0); const remainingRupiah = sale.totalRupiah - paidRupiah; return { ...sale, transactionDate: jakartaDate(sale.transactionDate), status: sale.status as SaleRecord["status"], paidRupiah, remainingRupiah, paymentStatus: derivePaymentStatus(remainingRupiah, paidRupiah, sale.dueDate, today), items, payments: payments.map((payment) => ({ ...payment, paidAt: payment.paidAt.toISOString() })) }; } catch (error) { dbError(error); } }
}
