import "server-only";
import { and, eq, ilike, or } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import * as schema from "@/db/schema";
import type { OwnerProfile } from "@/lib/auth/owner";
import type { SaleMutationInput } from "@/domain/sales";
import { RepositoryConflictError, RepositoryUnavailableError, type CalculatedSale, type CustomerRecord, type F2Repository, type SaleRecord } from "./repository";

type Db = NodePgDatabase<typeof schema>;
const customerColumns = { id: schema.customers.id, customerNumber: schema.customers.customerNumber, name: schema.customers.name, whatsapp: schema.customers.whatsapp, address: schema.customers.address, notes: schema.customers.notes, isActive: schema.customers.isActive };
const displayNumber = (prefix: string) => `${prefix}-${Date.now()}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`;
function isUniqueViolation(error: unknown): boolean {
  if (typeof error !== "object" || error === null) return false;
  if ("code" in error && error.code === "23505") return true;
  return "cause" in error && isUniqueViolation(error.cause);
}
function dbError(error: unknown): never { if (isUniqueViolation(error)) throw new RepositoryConflictError(); throw new RepositoryUnavailableError(); }

export class DrizzleF2Repository implements F2Repository {
  constructor(private readonly db: Db) {}
  async createCustomer(input: { name: string; whatsapp?: string; address?: string; notes?: string }, actor: OwnerProfile): Promise<CustomerRecord> { try { return await this.db.transaction(async (tx) => { const [record] = await tx.insert(schema.customers).values({ ...input, customerNumber: displayNumber("CUS") }).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), actorId: actor.id, entityType: "customer", entityId: record.id, action: "customer.created", after: record }); return record; }); } catch (error) { dbError(error); } }
  async updateCustomer(input: { id: string; name?: string; whatsapp?: string; address?: string; notes?: string }, actor: OwnerProfile): Promise<CustomerRecord | null> { try { return await this.db.transaction(async (tx) => { const [before] = await tx.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, input.id)).limit(1); if (!before) return null; const { id, ...changes } = input; const [record] = await tx.update(schema.customers).set({ ...changes, updatedAt: new Date() }).where(eq(schema.customers.id, id)).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), actorId: actor.id, entityType: "customer", entityId: id, action: "customer.updated", before, after: record }); return record; }); } catch (error) { dbError(error); } }
  async setCustomerActive(id: string, isActive: boolean, actor: OwnerProfile): Promise<CustomerRecord | null> { try { return await this.db.transaction(async (tx) => { const [before] = await tx.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, id)).limit(1); if (!before) return null; const [record] = await tx.update(schema.customers).set({ isActive, updatedAt: new Date() }).where(eq(schema.customers.id, id)).returning(customerColumns); await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), actorId: actor.id, entityType: "customer", entityId: id, action: isActive ? "customer.enabled" : "customer.archived", before, after: record }); return record; }); } catch (error) { dbError(error); } }
  async listCustomers(input: { query: string; includeArchived: boolean; limit: number; offset: number }): Promise<CustomerRecord[]> { try { const search = input.query ? or(ilike(schema.customers.name, `%${input.query}%`), ilike(schema.customers.customerNumber, `%${input.query}%`), ilike(schema.customers.whatsapp, `%${input.query}%`)) : undefined; const active = input.includeArchived ? undefined : eq(schema.customers.isActive, true); return await this.db.select(customerColumns).from(schema.customers).where(and(active, search)).orderBy(schema.customers.name).limit(input.limit).offset(input.offset); } catch (error) { dbError(error); } }
  async getCustomer(id: string): Promise<CustomerRecord | null> { try { const [record] = await this.db.select(customerColumns).from(schema.customers).where(eq(schema.customers.id, id)).limit(1); return record ?? null; } catch (error) { dbError(error); } }
  async findSaleByIdempotencyKey(key: string): Promise<SaleRecord | null> { try { const [sale] = await this.db.select({ id: schema.sales.id, invoiceNumber: schema.sales.invoiceNumber, idempotencyKey: schema.sales.idempotencyKey, totalRupiah: schema.sales.totalRupiah, paymentStatus: schema.sales.paymentStatus, status: schema.sales.status }).from(schema.sales).where(eq(schema.sales.idempotencyKey, key)).limit(1); if (!sale) return null; const rows = await this.db.select({ amount: schema.payments.amountRupiah }).from(schema.payments).where(eq(schema.payments.saleId, sale.id)); const paidRupiah = rows.reduce((sum, row) => sum + row.amount, 0); return { ...sale, paidRupiah, remainingRupiah: sale.totalRupiah - paidRupiah, paymentStatus: sale.paymentStatus as SaleRecord["paymentStatus"], status: sale.status as SaleRecord["status"] }; } catch (error) { dbError(error); } }
  async createSaleAtomic(input: SaleMutationInput, calculated: CalculatedSale, actor: OwnerProfile): Promise<SaleRecord> { try { return await this.db.transaction(async (tx) => {
    const invoiceNumber = displayNumber("INV"); const [sale] = await tx.insert(schema.sales).values({ invoiceNumber, idempotencyKey: input.idempotencyKey, customerId: input.customerId, status: input.status, paymentStatus: calculated.paymentStatus, transactionDate: new Date(`${input.transactionDate}T00:00:00+07:00`), dueDate: input.dueDate, subtotalRupiah: calculated.subtotalRupiah, discountRupiah: input.discountRupiah, feeRupiah: input.feeRupiah, totalRupiah: calculated.totalRupiah, notes: input.notes, confirmedAt: input.status === "confirmed" ? new Date() : null }).returning({ id: schema.sales.id });
    await tx.insert(schema.saleItems).values(calculated.items.map((item) => ({ saleId: sale.id, descriptionSnapshot: item.description, pricingBasis: item.pricingBasis, unitSnapshot: item.unitSnapshot, crateQuantity: item.crateQuantity, weightKg: item.weightKg, pricingQuantity: item.pricingQuantity, unitPriceRupiah: item.unitPriceRupiah, subtotalRupiah: item.subtotalRupiah })));
    if (calculated.paidRupiah > 0) await tx.insert(schema.payments).values({ paymentNumber: displayNumber("PAY"), saleId: sale.id, amountRupiah: calculated.paidRupiah, method: input.paymentMethod!, paidAt: new Date(), idempotencyKey: `${input.idempotencyKey}:initial` });
    await tx.insert(schema.auditEvents).values({ eventNumber: displayNumber("AUD"), actorId: actor.id, entityType: "sale", entityId: sale.id, action: input.status === "confirmed" ? "sale.confirmed" : "sale.drafted", after: { invoiceNumber, totalRupiah: calculated.totalRupiah, paidRupiah: calculated.paidRupiah } });
    return { id: sale.id, invoiceNumber, idempotencyKey: input.idempotencyKey, totalRupiah: calculated.totalRupiah, paidRupiah: calculated.paidRupiah, remainingRupiah: calculated.remainingRupiah, paymentStatus: calculated.paymentStatus, status: input.status };
  }); } catch (error) { dbError(error); } }
}
